name: "Setup Node.js and Install Dependencies"
description: "Sets up Node.js, configures Yarn, and installs dependencies"

runs:
  using: "composite"
  steps:
    - name: Git Safe Directory
      run: git config --global --add safe.directory /__w/book-cook/book-cook
      shell: bash

    - name: Set up Yarn
      run: yarn set version 1.22.1
      shell: bash

    - name: Install dependencies
      run: yarn install
      shell: bash

    - name: Cache Yarn Cache
      uses: actions/cache@v3
      with:
        path: .yarn/cache
        key: yarn-${{ github.sha }}
        restore-keys: |
          yarn-
