import { makeStyles, tokens } from "@fluentui/react-components";

export const useMonthDayCellStyles = makeStyles({
  dayCell: {
    display: "flex",
    flexDirection: "column",
    borderRight: `1px solid ${tokens.colorNeutralStroke1}`,
    borderBottom: `1px solid ${tokens.colorNeutralStroke1}`,
    backgroundColor: tokens.colorNeutralBackground1,
    position: "relative",
    overflowY: "hidden",
    "&:nth-child(7n)": {
      borderRight: "none",
    },
  },
  dayHeader: {
    padding: `${tokens.spacingVerticalXS} ${tokens.spacingHorizontalXS}`,
    textAlign: "left",
    backgroundColor: "transparent",
  },
  dayNumber: {
    fontSize: tokens.fontSizeBase200,
    fontWeight: tokens.fontWeightSemibold,
  },
  isToday: {},
  isTodayNumber: {
    backgroundColor: tokens.colorBrandBackground,
    color: tokens.colorNeutralForegroundOnBrand,
    borderRadius: "50%",
    width: "24px",
    height: "24px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: tokens.fontSizeBase200,
    fontWeight: tokens.fontWeightSemibold,
  },
  isTodayText: {
    color: tokens.colorBrandForeground1,
    fontWeight: tokens.fontWeightBold,
  },
  otherMonth: {
    opacity: 0.4,
  },
  pastDay: {
    opacity: 0.5,
    backgroundColor: tokens.colorNeutralBackground2,
  },
  pastDayHeader: {
    backgroundColor: "transparent",
  },
  isDraggingOver: {
    backgroundColor: tokens.colorBrandBackground2,
    border: `2px solid ${tokens.colorBrandStroke1}`,
  },
  mealIndicators: {
    flex: 1,
    padding: "2px",
    display: "flex",
    flexDirection: "column",
    gap: "1px",
    overflow: "hidden",
    minHeight: 0,
    maxHeight: "calc(120px - 24px)",
  },
  mealIndicator: {
    padding: "1px 4px 1px 2px",
    borderRadius: "2px",
    fontSize: "9px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "2px",
    height: "14px",
    maxHeight: "14px",
    minHeight: "14px",
    cursor: "pointer",
    position: "relative",
    backgroundColor: "transparent",
    flexShrink: 0,
    "&:hover": {
      transform: "scale(1.02)",
      "& .meal-remove-button": {
        opacity: 1,
      },
    },
  },
  mealContent: {
    display: "flex",
    alignItems: "center",
    gap: "2px",
    overflow: "hidden",
    flex: 1,
    paddingLeft: "2px",
  },
  mealEmoji: {
    fontSize: "8px",
    flexShrink: 0,
  },
  mealTitle: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    flex: 1,
    minWidth: 0,
  },
  removeButton: {
    minWidth: "12px",
    width: "12px",
    height: "12px",
    padding: "0",
    opacity: 0.6,
    transition: "opacity 0.2s ease",
    flexShrink: 0,
    backgroundColor: "transparent",
    borderRadius: "2px",
    border: "none",
    color: tokens.colorNeutralForeground3,
    "&:hover": {
      opacity: 1,
      backgroundColor: tokens.colorNeutralBackground2,
      color: tokens.colorNeutralForeground1,
    },
  },
});