// Centralized icon imports for better tree shaking
// Only import the specific icons we actually use
export {
  Heart20Regular,
  Heart20Filled,
  SparkleRegular,
  Add20Regular,
  Settings20Regular,
  PersonRegular,
  Search20Regular,
  Navigation20Regular,
  ChevronDown20Regular,
  ChevronUp20Regular,
  ChevronLeft20Regular,
  ChevronRight20Regular,
  MoreHorizontal20Regular,
  Delete20Regular,
  Edit20Regular,
  Share20Regular,
  Copy20Regular,
  Tag20Regular,
  Home20Regular,
  Food20Regular,
  Collections20Regular,
  Dismiss20Regular,
  CheckmarkRegular,
  SaveRegular,
  ErrorCircle20Regular,
  Info20Regular,
  Warning20Regular,
} from "@fluentui/react-icons";