name: Build and Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:18.19.0
    steps:
      - uses: actions/checkout@v3
      - name: Set up Yarn
        run: yarn set version 1.22.1
      - name: Install dependencies
        run: yarn install
      - name: Cache Yarn Cache
        uses: actions/cache@v3
        with:
          path: .yarn/cache
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-
      - name: Build and analyze bundle
        run: yarn analyze
      - name: Upload bundle stats
        uses: actions/upload-artifact@v4
        with:
          name: bundle-stats
          path: .next/analyze
      - name: Comment PR with bundle size changes
        uses: preactjs/compressed-size-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          pattern: ".next/static/**/*.js"
      - name: Lint
        run: yarn lint
