name: Build and Test
on: [push, pull_request]

jobs:
  build:
      image: node:18.19.0

    steps:
      - uses: actions/checkout@v2
      - name: Set up Yarn
        run: yarn set version 1.22.1
      - name: Install dependencies
        run: yarn install
      - name: Cache Yarn Cache
        uses: actions/cache@v2
        with:
          path: .yarn/cache
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn lint
