name: Build and Test
on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    container:
      image: node:18.19.0
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Git Safe Directory
        run: git config --global --add safe.directory /__w/book-cook/book-cook

      - name: Setup Node
        run: |
          yarn set version 1.22.1
          yarn install

      - name: Cache Yarn packages
        uses: actions/cache@v3
        with:
          path: .yarn/cache
          key: yarn-${{ github.sha }}
          restore-keys: |
            yarn-

      - name: Cache Next.js build cache
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: nextjs-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('next.config.js') }}
          restore-keys: |
            nextjs-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('next.config.js') }}
            nextjs-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Lint
        run: yarn lint

      - name: Build and analyze bundle
        run: yarn analyze

      - name: Upload bundle stats
        uses: actions/upload-artifact@v4
        with:
          name: bundle-stats
          path: .next/analyze

      - name: Comment PR with bundle size changes
        uses: preactjs/compressed-size-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          pattern: ".next/static/**/*.js"
          build-script: "analyze"
          use-check-if-exists: true
