name: "Chromatic"
on: 
  push:
  pull_request:
jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22.17.0
      - name: Install dependencies
        run: yarn
      - name: Check for Chromatic token
        id: chromatic-check
        run: |
          if [ -z "${{ secrets.CHROMATIC_PROJECT_TOKEN }}" ]; then
            echo "has-token=false" >> $GITHUB_OUTPUT
            echo "⚠️ CHROMATIC_PROJECT_TOKEN not set - skipping visual tests"
          else
            echo "has-token=true" >> $GITHUB_OUTPUT
            echo "✅ CHROMATIC_PROJECT_TOKEN found - running visual tests"
          fi
          
      - name: Run Chromatic
        uses: chromaui/action@latest
        if: steps.chromatic-check.outputs.has-token == 'true'
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true
          onlyChanged: true
