name: Build and Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:18.19.0

    steps:
      - uses: actions/checkout@v2
      - name: Install Yarn 1.22.17
        run: npm install -g yarn@1.22.17
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn lint
